fix custom icon selection
- select custom icon and search for an app
- seach text that doesn't give any results produces an exception because mIconGrid isn't aware of changed/empty data when setting visibilty
```
2021-11-05 20:42:13.853 31097-31097/fr.neamar.kiss.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fr.neamar.kiss.debug, PID: 31097
    java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
        at java.util.ArrayList.get(ArrayList.java:437)
        at fr.neamar.kiss.CustomIconDialog$IconAdapter.getItem(CustomIconDialog.java:346)
        at fr.neamar.kiss.CustomIconDialog$IconAdapter.getItemId(CustomIconDialog.java:356)
        at android.widget.AdapterView.getItemIdAtPosition(AdapterView.java:815)
        at android.widget.AdapterView.setNextSelectedPositionInt(AdapterView.java:1247)
        at android.widget.GridView.setSelectionInt(GridView.java:1630)
        at android.widget.AbsListView.resurrectSelection(AbsListView.java:5551)
        at android.widget.AbsListView.onFocusChanged(AbsListView.java:2022)
        at android.widget.GridView.onFocusChanged(GridView.java:1959)
        at android.view.View.handleFocusGainInternal(View.java:7463)
        at android.view.ViewGroup.handleFocusGainInternal(ViewGroup.java:818)
        at android.view.View.requestFocusNoSearch(View.java:12426)
        at android.view.View.requestFocus(View.java:12400)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3262)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3314)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3263)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3314)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3263)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3314)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3263)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3314)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3268)
        at android.view.View.requestFocus(View.java:12367)
        at android.view.View.requestFocus(View.java:12309)
        at android.view.View.rootViewRequestFocus(View.java:7647)
        at android.view.View.clearFocusInternal(View.java:7633)
        at android.view.View.clearFocus(View.java:7609)
        at android.view.View.setFlags(View.java:15191)
        at android.view.View.setVisibility(View.java:10836)
        at fr.neamar.kiss.CustomIconDialog.refreshList(CustomIconDialog.java:309)
        at fr.neamar.kiss.CustomIconDialog.access$100(CustomIconDialog.java:53)
        at fr.neamar.kiss.CustomIconDialog$1.lambda$onTextChanged$0$fr-neamar-kiss-CustomIconDialog$1(CustomIconDialog.java:143)
        at fr.neamar.kiss.CustomIconDialog$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```